version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers

    working_directory: ~/magento

    steps:

    - run:
            name: Setup test environment
            command: |
                  sudo apt-get install -y libpng-dev
                  sudo -E docker-php-ext-install gd
                  sudo -E docker-php-ext-install bcmath
                  sudo apt-get install -y libmcrypt-dev
                  sudo apt-get install -y libxslt-dev
                  sudo -E docker-php-ext-install xsl
                  sudo -E docker-php-ext-install pdo_mysql
                  sudo -E docker-php-ext-install soap
    - run:
            name: Setup composer details
            command: |
                  export COMPOSER_MEMORY_LIMIT=-1
                  sudo composer self-update
                  mkdir ~/.composer
                  touch ~/.composer/auth.json
                  echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_KEY}\",\"password\":\"${MAGENTO_SECRET}\"}}}" > ~/.composer/auth.json
                  composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition . 2.3.4
                  composer require mpdf/mpdf
                  composer require eadesignro/module-eacore
                  mkdir -p app/code/Eadesigndev/Pdfgenerator
    - checkout:
            path: app/code/Eadesigndev/Pdfgenerator

    - run:
            name: Install marketplace quality tools
            command: |
                  php bin/magento module:enable --all
                  php -d memory_limit=6G bin/magento setup:di:compile
                  composer create-project --repository=https://repo.magento.com magento/marketplace-eqp magento-coding-standard
                  php magento-coding-standard/vendor/bin/phpcs --standard=app/code/Eadesigndev/Pdfgenerator/Test/Php/_files/phpcs/ruleset.xml app/code/Eadesigndev/Pdfgenerator/Api/ app/code/Eadesigndev/Pdfgenerator/Block/ app/code/Eadesigndev/Pdfgenerator/Controller/ app/code/Eadesigndev/Pdfgenerator/Helper/ app/code/Eadesigndev/Pdfgenerator/Model/ app/code/Eadesigndev/Pdfgenerator/Setup/ app/code/Eadesigndev/Pdfgenerator/Test/ app/code/Eadesigndev/Pdfgenerator/Ui/ app/code/Eadesigndev/Pdfgenerator/view/
                  php vendor/bin/phpmd app/code/Eadesigndev/Pdfgenerator/Api/,app/code/Eadesigndev/Pdfgenerator/Block/,app/code/Eadesigndev/Pdfgenerator/Controller/,app/code/Eadesigndev/Pdfgenerator/Helper/,app/code/Eadesigndev/Pdfgenerator/Model/,app/code/Eadesigndev/Pdfgenerator/Setup/,app/code/Eadesigndev/Pdfgenerator/Ui/,app/code/Eadesigndev/Pdfgenerator/view/ text  app/code/Eadesigndev/Pdfgenerator/Test/Php/_files/phpmd/ruleset.xml
                  php vendor/bin/phpunit app/code/Eadesigndev/Pdfgenerator/Test/ --config dev/tests/unit/phpunit.xml.dist --coverage-clover=app/code/Eadesigndev/Pdfgenerator/build/logs/clover.xml
